### ISSUE TITLE
Syncthing on Scientific Linux 7 (EL7) - cannot start service

### ISSUE THREAD

**Issue by jmp242** [decathorpe/fedora-pkgs#3]
I am not super familiar with the systemd services having used SysV init in 6 and previous, but I tried the instructions as my user: 
systemctl --user enable syncthing.service
Failed to execute operation: Process /bin/false exited with status 1
(same for start)

I also tried as root. I'm not sure if this is a bug or user error.

**Comment by decathorpe** [comment]
I'm not really sure how systemd works on CentOS derivatives, but I am sure we can work this out --

Can you verify if a systemd process is running for your user or not?

There should be at least one for "root", which is PID 1 (init), and maybe some for other users - but that depends on the systemd version / configuration and that may be the reason why ```systemd --user SOMETHING``` doesn't work in this case.

**Comment by jmp242** [comment]
So:
ps aux | grep systemd
root         1  0.0  0.0  41716  4124 ?        Ss   Apr11   4:53 
/usr/lib/systemd/systemd --system --deserialize 17
root       594  0.0  0.0  43904  2120 ?        Ss   Apr11   0:01 
/usr/lib/systemd/systemd-udevd
dbus       893  0.0  0.0  48700  2908 ?        Ss   Apr11   4:27 
/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile 
--systemd-activation
root      1007  0.0  0.0  36764  1736 ?        Ss   Apr11   1:10 
/usr/lib/systemd/systemd-logind
root     16417  0.0  0.0 112648   960 pts/1    S+   09:49   0:00 grep 
--color=auto systemd
root     22786  0.0  0.1  61396 16284 ?        Ss   Apr11   5:54 
/usr/lib/systemd/systemd-journald

It looks like root is running a process? No other users though.

James Pulver
CLASSE Computer Group
Cornell University

**Comment by decathorpe** [comment]
Okay, that might explain your problem.

Can you try
```sudo systemctl enable syncthing@$USER.service```
and tell me if that works? You might have to replace the environment variable $USER with your actual username.

**Comment by jmp242** [comment]
Ah ha, looks like that may have worked. I did: systemctl enable 
syncthing@jmp242.service as root and:
Created symlink from 
/etc/systemd/system/multi-user.target.wants/syncthing@jmp242.service to 
/usr/lib/systemd/system/syncthing@.service.

I'm guessing this is what I need, and it probably will do what I want.


James Pulver
CLASSE Computer Group
Cornell University

**Comment by decathorpe** [comment]
It should. You just have to consider this starts syncthing at system startup and not when you are logging in.

Additionally, you can't use the GUI restart buttons for the daemon this way, but have to use ```systemctl restart syncthing@$USER.service``` manually.

Otherwise the behaviour should be the same.
Closing the issue now.
