### ISSUE TITLE
syncthing copr is failing builds

### ISSUE THREAD

**Issue by pszypowicz** [decathorpe/fedora-pkgs#4]
Hi,

First of all thanks for your syncthing copr repo, its really usefull!

Currently build are failing, and it looks like its because of lack of few go packages: 
(https://copr-be.cloud.fedoraproject.org/results/decathorpe/syncthing/fedora-23-x86_64/00322613-syncthing/build.log.gz)

**Comment by decathorpe** [comment]
Hm, that's odd, I must have forgot to look at the build output. Usually I don't leave unsuccessful builds up.

I'll look into adding the missing packages to the build.

Also, I find it odd that they add dependencies during the stable branch without mentioning it in release notes (which I check before building new versions).

**Comment by decathorpe** [comment]
I adapted the .spec file to use the bundled dependency sources. This should also avoid future breakage. A new build of 0.13.5 has been uploaded.
