### ISSUE TITLE
syncthing 0.14.8 fails on f23 - probably Go 1.5 too old

### ISSUE THREAD

**Issue by azrdev** [decathorpe/fedora-pkgs#5]
The [syncthing 0.14.8 build](https://copr.fedorainfracloud.org/coprs/decathorpe/syncthing/build/460921/) fails (only) for fedora 23. The [build log](https://copr-be.cloud.fedoraproject.org/results/decathorpe/syncthing/fedora-23-x86_64/00460921-syncthing/build.log.gz) contains the line

> cmd/syncthing/main.go:285: undefined: debug.SetTraceback

According to [these release notes](https://blog.golang.org/go1.6) `debug.SetTraceback` was added to Go in version 1.6, while [fedora 23 ships 1.5](https://apps.fedoraproject.org/packages/golang).

**Comment by decathorpe** [comment]
Yep, I suspected Go 1.5 was too old on f23. So ... basically I can't really do anything about that.

I guess you can use the pre-compiled release from the syncthing homepage, though.

**Comment by azrdev** [comment]
@decathorpe this has been fixed, see the linked issue. I suppose I'll have to wait till the next release for a working build?

**Comment by decathorpe** [comment]
I guess - as soon as a release is available, I'll package it up quickly, as usual :smile:
I'll re-open the issue for now, and close it when the stable release fixing this arrives.

**Comment by decathorpe** [comment]
I uploaded a build of the new syncthing 0.14.9 to the repository, which fixes this issue. :)
