### ISSUE TITLE
Consider adding QSyncthingTray

### ISSUE THREAD

**Issue by dralley** [decathorpe/fedora-pkgs#7]
https://github.com/sieren/QSyncthingTray

**Comment by decathorpe** [comment]
Done - though f26 builds don't work in COPR right now, and EPEL7 doesn't have provide all dependencies.

The project's build system is a bit weird (it doesn't support `make install`, for example), so I hope everything works as intended.

Also, I wrote and included a simple `.desktop` file that can be copied from `/usr/share/applications/` to `$HOME/.config/autostart/` to enable starting the tray icon at login.

If there's anything wrong with / missing in the package, feel free to just open an issue here!
