### ISSUE TITLE
Build of syncthing for Fedora 26?

### ISSUE THREAD

**Issue by piotr-dobrogost** [decathorpe/fedora-pkgs#8]
Are there any plans to enable builds of syncthing for Fedora 26 (Branched)?

**Comment by decathorpe** [comment]
If you look at https://copr.fedorainfracloud.org/coprs/decathorpe/syncthing/monitor/, you'll see that syncthing is built for f26 already.

**Comment by piotr-dobrogost** [comment]
Thanks for reply and I'm sorry for confusion. Copr's web interface is confusing. I would expect the list of recent builds in _Monitor_ tab and list of all kinds of packages in _Packages_ tab and not vice versa...
