### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by IvanTurgenev** [decathorpe/fedora-pkgs#9]
I have a raspberry i was wondering maybe you could build ARMv7h?

**Comment by decathorpe** [comment]
I assume you are talking about a syncthing package - COPR doesn't provide infrastructure for ARMv7 builds, but I'm working on making an official syncthing package for fedora (tracked at [RHBZ#1427634](https://bugzilla.redhat.com/show_bug.cgi?id=1427634)). That work is nearly finished, and an official fedora package would also include builds for ARM.
